language: python
sudo: false
python:
  - 3.7.4
env:
  - FLASK_APP=app.py

before_install:
  - pip install poetry
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install: 
  - make install

script:
  - flask load-section-questions bars
  - flask load-section-questions minimum
  - make lint
  - make test
