language: python
sudo: false
python:
  - 3.7
env:
  - FLASK_APP=main.py

before_install:
  - pip install poetry
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install: 
  - make install

script:
  - make lint