[tool.poetry]
name = "junior"
version = "0.1.0"
description = ""
authors = ["Alexey Lebedev <alexey.lebedev@fogstream.ru>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
